# Generated by Django 4.0.1 on 2022-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flower_name', models.CharField(max_length=50)),
                ('Introduction', models.TextField()),
                ('Etymology', models.TextField()),
                ('Evolution', models.TextField()),
                ('Species', models.TextField()),
                ('Taxonomy', models.TextField()),
                ('Ornamental_plants', models.TextField()),
                ('Cut_flowers', models.TextField()),
                ('Medicinal_uses', models.TextField()),
                ('Health_benefit', models.TextField()),
                ('Perfumes_food', models.TextField()),
                ('Symbolizes', models.TextField()),
                ('Season_to_grow', models.TextField()),
            ],
        ),
    ]
